project_name: "transformer-wmt17"
run_name: "wmt17-sinusoidal-run"
weights_dir: "./weights_sinusoidal"
batch_size: 64
epochs: 5
learning_rate: 1.0
max_seq_length: 100
vocab_size: 32000
d_model: 512
n_heads: 8
num_encoder_layers: 6
num_decoder_layers: 6
dim_feedforward: 2048
dropout: 0.1
mixed_precision: true
dataset_name: "wmt17"
dataset_config: "de-en"
val_split_size: 0.01
resume_from: null
start_epoch: 0
warmup_steps: 4000
use_scheduler: true
use_wandb: true
positional_encoding_type: "sinusoidal"

data:
  dataset_version: "wmt17"
  train_val_test_split: "train/validation/test"
  
tokenizer:
  type: "BPE" 
  implementation: "huggingface/tokenizers"
  vocab_size: 32000
  normalization: false 
  special_tokens:
    bos: "[BOS]" 
    eos: "[EOS]"
    pad: "[PAD]"
    unk: "[UNK]"

preprocessing:
  max_seq_length: 100 
  min_seq_length: 1
  filter_long_sentences: false 
  normalization: "none"
